### ISSUE TITLE
Get Google Login required data

### ISSUE THREAD

**Issue by somarkn99** [Syrian-Open-Source/social-api#2]
You must specify the information required to bring user information from his Google account, keep in mind that the token will be sent from the Client side (frontend - flutter) and our mission here is only to send it to Google and bring information based on it.
After identifying the information, add it to the class assigned to it, and do not forget if it is general information to define it in the father's class as well so that the other colleagues will determine their required information as well

if there is a scopes you should make it controllable from our side

**Comment by Marikamal** [comment]
i will take this task
