### ISSUE TITLE
Get GitHub Login required data

### ISSUE THREAD

**Issue by somarkn99** [Syrian-Open-Source/social-api#4]
You must specify the information required to bring user information from his GitHub account, keep in mind that the token will be sent from the Client side (frontend - flutter) and our mission here is only to send it to GitHub and bring information based on it.
After identifying the information, add it to the class assigned to it, and do not forget if it is general information to define it in the father's class as well so that the other colleagues will determine their required information as well

if there is a scope you should make it controllable from our side

**Comment by HomamHaidar** [comment]
I will take this task
